spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:h2:file:./data/chatdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    nz.coreyh.springchat: DEBUG